### PR TITLE
Basic async support

### PR DESCRIPTION
**Pull request by GnomedDev**
### Please create an async branch on upstream, so I can swap the PR target to that, this shouldn't replace master.
I have spent the time and replaced `subprocess.run` with `asyncio.subprocess.create_subprocess_shell` in `Voice._phonemes_to_audio` and `_str_to_phonemes`, I also replaced urllib with aiohttp (massively speeding up voice_install.py).

#### Notes:
- For massive strings (eg: "Hello World! "*10000) it may block for significant time (~250ms), although this is much better then previously (2 seconds)
- voice_install.py now uses an f-string, as I don't understand the old string formatting style used (and min version is 3.5 for f-strings)
- Zombie Processes may be created, however I have taken great precautions to stop it
- 5 tests seem to fail locally, however this may be due to my weird dev setup
- Docs have not been updated, I don't know how to

### CODE REVIEW

**Comment by hadware** [comment]
This is awesome! I'll create an async branch as requested, and try and merge your additions into the main package as best as I can :)

**Comment by hadware** [comment]
It's all good, go ahead and make your new PR.

**Comment by GnomedDev** [comment]
Do the tests pass for you? And on the subject of fstrings, should I make a PR to master and this branch to replace the % formatting with fstrings?

**Comment by hadware** [comment]
I'll have to enable tests on PR's, but for now they're broken even on the main branch since the target audio files don't have the same sound level as the default ones (as a consequence of your recent PR on volume config, but that's on me to fix that, just haven't had the time to do it yet).

**Comment by GnomedDev** [comment]
ah, makes sense, what's blocking this from being merged? docs?

**Comment by hadware** [comment]
Oh sorry i didn't notice that you already changed the branch, i didn't know we could do that (I was waiting for a new PR )

**Comment by GnomedDev** [comment]
Hey, can we talk via Discord about some ideas I have, my username#tag is `Gnome!#6669`

**Comment by hadware** [comment]
Sure! sorry, I was AFK. I sent you a friend request on discord.

**Pull request merged**
